name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-Python@v2
        with:
          Python-version: 3.x

      - name: Install Sphinx
        run: pip install sphinx sphinx_rtd_theme

      - name: Build documentation
        run: sphinx-build doc _build
  
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-Python@v2
        with:
          Python-version: 3.x

      - name: Install Pylint
        run: pip install pylint

      - name: run Pylint
        run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')

  format:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-Python@v2
        with:
          Python-version: 3.x

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black --diff --check $(git ls-files '*.py')

    test:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-Python@v2
        with:
          Python-version: 3.x

      - name: Install pytest
        run: pip install pytest

      - name: Run pytest
        run: pytest

      - name: Run unittest
        run: python -m unittest discover
         

  
